#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8571
spring:
  profiles: dev # 开发环境
  application:
    name: ja-display-8571			# ******服务名******

---
server:
  port: 8571
spring:
  profiles: prod # 生产环境
  application:
    name: ja-display-8571			# ******服务名*******

 
